
// eslint-disable-next-line unicorn/filename-case
import * as React from "react";
import Logo from "../../../SDGLogos/Goal-SDG07.png";
import { QuizProps } from "../../../Interfaces/SDG";

export const SDG07_Quiz: QuizProps = {
    sdgNumber: 7,
    sdgTitle: "Stromverbrauch im Haushalt",
    sdg: "SDG07",
    logo: Logo,
    tile: {
        1: "Einleitung",
        8: "Schlussfolgerung",
        9: "Anleitung",
        16: "Schlussfolgerung",
    },
    text: {
        1: <p style={{ fontSize: "2vw" }}>Es gibt mittlerweile viele Dinge, die Strom brauchen, damit sie funktionieren. Dabei benötigen sie unterschiedliche Mengen an Strom, was man auch „Leistung“ nennt. Diese wird in der Einheit „Watt“ festgelegt. Wenn man nun über den Stromverbrauch während einer bestimmten Zeit redet, nimmt man die Leistung (Einheit W für Watt) des gemessenen Geräts mal die vergangene Zeit (Einheit h für Stunden) und bekommt als Ergebnis Wattstunden (Einheit Wh). Überlegt euch nun bei den folgenden Geräten, welche der beiden angegebenen Zahlen an Kilowattstunden kWh (Wattstunden mal 1000) wahrscheinlicher ist. Wenn ihr auf “Überprüfen“ tippt, seht ihr die Lösung.</p>,
        8: <p>Das ist ziemlich viel Strom, oder? Um das einmal anders auszudrücken: mit 1 kWh könnte man sich etwa eine Stunde die Haare föhnen oder 100 Stunden Radio hören. Das heißt, dass wir mit dem Stromverbrauch von einem Fernseher für eine Stunde 190 Stunden Haare föhnen oder 1.900 Stunden Radio hören könnten.</p>,
        9: <p>Als Nächstes werden euch verschiedene Energieträger, also Stoffe, deren Energie nutzbar gemacht wird, gezeigt. Überlegt euch jetzt bei diesen, wie viel Prozent sie von dem weltweiten Energieverbrauch 2018 ausgemacht haben. Tippt auf eine der zwei Prozentzahlen und anschließend auf “Überprüfen“, um die Lösung zu sehen.</p>,
        17: <p>Dabei ist jedoch nur die Energie aus Biokraftstoff/Abfall, Wasserkraft und aus den anderen Energieträgern nachhaltig und erneuerbar. Den Großteil des Stroms beziehen wir aus sogenannten fossilen Energieträgern (Erdöl, Kohle/Torf, Erdgas), die verbrannt werden, um ihre Energie zu gewinnen. Die dabei ausgestoßenen Gase schaden aber der Umwelt und treiben den Klimawandel voran. Das Problem ist, dass das Erdöl, die Kohle und das Erdgas nur einmal verwendet werden können und in einigen Jahrzehnten aufgebraucht sein werden. Deshalb ist es so wichtig, dass wir mehr erneuerbare Energie benutzen, aber auch insgesamt weniger Strom verbrauchen.</p>,
    },
    question: {
        2: "Wie viele Kilowattstunden kWh pro Jahr verbraucht ein elektrischer Herd?",
        3: "Wie viele Kilowattstunden kWh pro Jahr verbraucht ein Kühlschrank?",
        4: "Wie viele Kilowattstunden kWh pro Jahr verbraucht eine Lampe?",
        5: "Wie viele Kilowattstunden kWh pro Jahr verbraucht ein Geschirrspüler?",
        6: "Wie viele Kilowattstunden kWh pro Jahr verbraucht eine Waschmaschine?",
        7: "Wie viele Kilowattstunden kWh pro Jahr verbraucht ein Fernseher?",
        10: "Wie viel Prozent hat Erdöl als Energieträger, das ist ein Stoff, dessen Energie nutzbar gemacht wird, von dem weltweiten Energieverbrauch 2018 ausgemacht?",
        11: "Wie viel Prozent hat Kohle / Torf als Energieträger von dem weltweiten Energieverbrauch 2018 ausgemacht?",
        12: "Wie viel Prozent hat Erdgas als Energieträger von dem weltweiten Energieverbrauch 2018 ausgemacht?",
        13: "Wie viel Prozent hat Biokraftstoff / Abfall als Energieträger von dem weltweiten Energieverbrauch 2018 ausgemacht?",
        14: "Wie viel Prozent hat Kernenergie von dem weltweiten Energieverbrauch 2018 ausgemacht?",
        15: "Wie viel Prozent hat Wasserkraft von dem weltweiten Energieverbrauch 2018 ausgemacht?",
        16: "Wie viel Prozent haben andere Energieträger (z. B.: Wind, Wärme) von dem weltweiten Energieverbrauch 2018 ausgemacht?",
    },
    buttonLeftContent: {
        2: <p>445 kWh</p>,
        3: <p>660 kWh</p>,
        4: <p>450 kWh</p>,
        5: <p>245 kWh</p>,
        6: <p>350 kWh</p>,
        7: <p>190 kWh</p>,
        10: <p>43 %</p>,
        11:  <p>14 %</p>,
        12:  <p>23 %</p>,
        13:  <p>27 %</p>,
        14:  <p>5 %</p>,
        15:  <p>2 %</p>,
        16:  <p>9 %</p>,
    },
    buttonRightContent: {
        2: <p>955 kWh</p>,
        3: <p>330 kWh</p>,
        4: <p>330 kWh</p>,
        5: <p>785 kWh</p>,
        6: <p>200 kWh</p>,
        7: <p>360 kWh</p>,
        10: <p>32 %</p>,
        11:  <p>27 %</p>,
        12:  <p>39 %</p>,
        13:  <p>9 %</p>,
        14:  <p>16 %</p>,
        15:  <p>62 %</p>,
        16:  <p>2 %</p>,
    },
    answerNumbersLeft: {
        2: "Richtig",
        3: "Falsch",
        4: "Falsch",
        5: "Richtig",
        6: "Falsch",
        7: "Richtig",
        10: "Falsch",
        11:  "Falsch",
        12:  "Richtig",
        13:  "Falsch",
        14:  "Richtig",
        15:  "Richtig",
        16:  "Falsch",
    },
    answerNumbersRight: {
        2: "Falsch",
        3: "Richtig",
        4: "Richtig",
        5: "Falsch",
        6: "Richtig",
        7: "Falsch",
        10: "Richtig",
        11:  "Richtig",
        12:  "Falsch",
        13:  "Richtig",
        14:  "Falsch",
        15:  "Falsch",
        16:  "Richtig",
    },
    explanation: {
        2: "Ein elektrischer Herd hat einen Verbrauch von 445 kWh pro Jahr.",
        3: "Ein Kühlschrank hat einen Verbrauch von 330 kWh pro Jahr.",
        4: "Eine Lampe hat einen Verbrauch von 330 kWh pro Jahr.",
        5: "Ein Geschirrspüler hat einen Verbrauch von 245 kWh pro Jahr.",
        6: "Eine Waschmaschine hat einen Verbrauch von 200 kWh pro Jahr.",
        7: "Ein Fernseher hat einen Verbrauch von 190 kWh pro Jahr.",
        10: "Erdöl als Energieträger machte 32 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
        11:  "Kohle / Torf als Energieträger machte 27 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
        12:  "Erdgas als Energieträger machte 23 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
        13:  "Biokraftstoff / Abfall als Energieträger machte 9 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
        14:  "Kernenergie machte 5 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
        15:  "Wasserkraft machte 2 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
        16:  "Andere Energieträger (z. B.: Wind, Wärme) machten 2 Prozent von dem weltweiten Energieverbrauch 2018 aus.",
    },
    // modalContent: <div>Quiz SDG 07</div>,
    isQuizActive: {
        1: false,
        2: true,
        3: true,
        4: true,
        5: true,
        6: true,
        7: true,
        8: false,
        9: false,
        10: true,
        11: true,
        12: true,
        13: true,
        14: true,
        15: true,
        16: true,
        17: false,

    }
}