// eslint-disable-next-line eslint-comments/disable-enable-pair
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable unicorn/filename-case */
import { QuizProps } from "../../../Interfaces/SDG";
import Logo from  "../../../SDGLogos/Goal-SDG05.png";

export const SDG05_Einstieg:QuizProps = {
    sdgNumber: 5,
    sdgTitle: "Geschlechtergleichheit",
    sdg: "SDG05",
    logo: Logo,
    tile: { 
        1: "Einleitung",
        2: "Einleitung", 
        3: "Einleitung",
        4: "Einleitung",
        5: "Einleitung",
        6: "Einleitung",
        7: "Einleitung",
        8: "Einleitung",
        9: "Einleitung",
        10: "Einleitung",
        11: "Einleitung",
        12: "Einleitung",
        13: "Schlusswort"
    },
    text: { 1: <p>Hallo! Lasst uns ein kleines Spiel spielen!</p>,
            2: <p>Ihr sollt euch zu jedem der Berufe überlegen, ob ihr es euch vorstellen könntet, sie später zu wählen. Anschließend positioniert ihr euch im Raum für drei ausgewählte Berufe. Ihr stellt euch auf eine der beiden gegenüberliegenden Seiten des Raumes. Die eine repräsentiert „Ja, das kann ich mir (gut) vorstellen“, die andere „Nein, das kann ich mir nicht (gut) vorstellen“. Schaut doch dann mal, wie viele Jungen und Mädchen sich welchen Beruf vorstellen können! Vielleicht können sich einen Beruf deutlich mehr Mädchen als Jungen vorstellen (oder anders herum), vielleicht ist alles aber auch einigermaßen ausgeglichen.</p>,
            3: <p>In den Lösungen könnt ihr eure Ergebnisse, welcher Beruf mehr mit welchem Geschlecht assoziiert wird, vergleichen mit den generellen Tendenzen, welches Geschlecht den Job eher ausübt. Die genauen Zahlen, die in der Lösung kommt, sind immer aus bestimmten Ländern (die Zahlen können auch auf viele andere Länder ungefähr übertragen werden), um euch zu zeigen, wie stark die Tendenz bei den einzelnen Berufen tatsächlich ist.</p>,
            13: <p>Ihr habt jetzt selbst gemerkt, dass manche Berufe sehr sehr typisch für ein bestimmtes Geschlecht sind. Zu der Geschlechtergleicheit, und wie man diese erreicht, erfahrt ihr gleich noch mehr</p>
    },
    question: { 4: "Kranken- bzw. Altenpfleger:in wird eher assoziiert mit ...",
                5: "Elektroniker:in wird eher assoziiert mit ...",
                6: "Maurer:in wird eher assoziiert mit ...",
                7: "Sprechstundenhelfer:in bzw. medizinische:r Fachangestellte:r wird eher assoziiert mit ...",
                8: "Friseur:in wird eher assoziiert mit ...",
                9: "Dachdecker:in wird eher assoziiert mit ...",
                10: "Sekretär:in bzw. Bürokraft wird eher assoziiert mit...",
                11: "Politiker:in wird eher assoziiert mit...",
                12: "Berufsfeuerwehrmann:frau wird eher assoziiert mit...",
            },
    buttonLeftContent: { 4: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                         5: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                         6: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                         7: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                         8: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                         9: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                        10: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                        11: <div style ={{ fontSize: "10vh" }}>Männern</div>,
                        12: <div style ={{ fontSize: "10vh" }}>Männern</div>, },
    buttonRightContent: { 4: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                          5: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                          6: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                          7: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                          8: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                          9: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                         10: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                         11: <div style ={{ fontSize: "12vh" }}>Frauen</div>,
                         12: <div style ={{ fontSize: "12vh" }}>Frauen</div>, },
    answerNumbersLeft: { 4: "Falsch",
                         5: "Richtig",
                         6: "Richtig",
                         7: "Falsch",
                         8: "Falsch",
                         9: "Richtig",
                        10: "Falsch",
                        11: "Richtig (obwohl es gleichmäßiger wird)",
                        12: "Richtig",
                        },
    answerNumbersRight:{ 4: "Richtig",
                         5: "Falsch",
                         6: "Falsch",
                         7: "Richtig",
                         8: "Richtig",
                         9: "Falsch",
                        10: "Richtig",
                        11: "Falsch (obwohl es gleichmäßiger wird)",
                        12: "Falsch",
                        },
   explanation:{ 4: "Von 20 Kranken- bzw. Altenpfleger:innen waren 2010 in Österreich im Schnitt 3 Männer dabei.",
                 5: "Von 25 Elektroniker:innen waren 2010 in Österreich im Schnitt 3 Männer dabei.",
                 6: "Von 200 Maurer:innen war 2010 in Deutschland im Schnitt eine Frau dabei. ",
                 7: "Von 100 Sprechstundenhelfer:innen war 2010 in Deutschland im Schnitt ein Mann dabei.",
                 8: "Von 10 Friseur:innen waren 2010 im Schnitt in Deutschland und Österreich 9 Frauen und nur ein Mann.",
                 9: "Von 200 Dachdecker:innen war 2010 in Deutschland im Schnitt eine Frau dabei. ",
                10: "In Deutschland waren 2010 im Schnitt 3 von 4 Bürokräften Frauen.",
                11: "Von 15 Poltiker:innen waren in Europa 2014 im Schnitt ca. 5-6 weiblich (früher waren es teilweise sogar nur eine von sechzehn).",
                12: "Von 50 Berufsfeuerwehrleuten war 2010 in Deutschland im Schnitt 1 Frauen dabei.",
                },
    // modalContent: <div>Einstieg Geschlechtergleichheit</div>,
    isQuizActive: {
        1: false,
        2: false,
        3: false,
        4: true,
        5: true,
        6: true,
        7: true,
        8: true,
        9: true,
        10: true,
        11: true,
        12: true,
        13: false,
    }
    /* eslint-enable unicorn/filename-case */ 
}